// This file is generated by Slice Machine. Update with care!

import BackButton from './BackButton';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	BackButton,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	back_button: BackButton,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
